import { useEffect, useState } from 'react';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Loader2, ShieldCheck } from 'lucide-react';
import { MultiFileUpload } from '@/components/ui/MultiFileUpload';
import { BulkSignoffPreview } from '@/components/review/BulkSignoffPreview';
import type { ImpactSummary } from '@/lib/bulkSignoffImpact';

const MIN_REMARK = 10;
const MAX_REMARK = 500;
const MAX_FILES = 5;

export interface BulkApproveSubmit {
  reason: string;
  attachmentUrls: string[];
  batchId: string;
}

interface Props {
  open: boolean;
  cellCount: number;
  batchId: string;            // generated by parent, kept stable while dialog open
  uploaderUserId: string;     // for storage folder scoping
  isLoading: boolean;
  onCancel: () => void;
  onConfirm: (payload: BulkApproveSubmit) => void;
  /**
   * 'approve' = terminal Management approval (default; keeps existing copy).
   * 'signoff' = intermediate stage sign-off (Manager/Skip-Level/HR PMS/Auditor).
   */
  mode?: 'approve' | 'signoff';
  /** Stage label shown in the sign-off title, e.g. "HR PMS". */
  stageLabel?: string;
  /** Sign-off only: per-cell + per-employee impact preview. */
  preview?: ImpactSummary | null;
  previewLoading?: boolean;
  previewError?: string | null;
}

/**
 * Bulk Approve dialog — replaces the plain confirm.
 * - Mandatory remark (≥10 chars) shared across all approved cells.
 * - Optional shared evidence (≤5 files) appended to every approved cell.
 * - Files are uploaded BEFORE the RPC fires (URLs handed to onConfirm).
 */
export function BulkApproveDialog({
  open, cellCount, batchId, uploaderUserId,
  isLoading, onCancel, onConfirm,
  mode = 'approve',
  stageLabel,
  preview = null,
  previewLoading = false,
  previewError = null,
}: Props) {
  const [reason, setReason] = useState('');
  const [urls, setUrls] = useState<string[]>([]);

  // Reset local state every time the dialog opens with a new batch.
  useEffect(() => {
    if (open) {
      setReason('');
      setUrls([]);
    }
  }, [open, batchId]);

  const trimmedLen = reason.trim().length;
  const remarkValid = trimmedLen >= MIN_REMARK;
  const skippedCount = preview?.totals.skippedCount ?? 0;
  const actionableCount = Math.max(0, cellCount - skippedCount);
  const canSubmit = remarkValid && !isLoading && actionableCount > 0;

  const isSignoff = mode === 'signoff';
  const verb = isSignoff ? 'Sign off' : 'Approve';
  const verbing = isSignoff ? 'Signing off' : 'Approving';
  const titleSuffix = isSignoff && stageLabel ? ` as ${stageLabel}` : '';

  const handleConfirm = () => {
    if (!canSubmit) return;
    onConfirm({ reason: reason.trim(), attachmentUrls: urls, batchId });
  };

  return (
    <Dialog open={open} onOpenChange={(o) => { if (!o && !isLoading) onCancel(); }}>
      <DialogContent className="sm:max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-primary" />
            Bulk {verb.toLowerCase()} {cellCount} cell{cellCount === 1 ? '' : 's'}{titleSuffix}?
          </DialogTitle>
          <DialogDescription>
            {isSignoff ? (
              <>
                The previous stage's score is carried forward to{' '}
                <strong>{stageLabel ?? 'this stage'}</strong>. Your remark and
                any supporting evidence are saved on every signed-off cell and
                the workflow advances to the next pending stage.
              </>
            ) : (
              <>
                Final scores will be stamped from the highest-priority completed stage
                (Auditor &gt; HR PMS &gt; Skip-Level &gt; Manager). Per Policy §88 this is
                immutable except via Re-open. Approved cells move to{' '}
                <strong>APPROVED</strong> immediately.
              </>
            )}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {isSignoff && (
            <BulkSignoffPreview
              preview={preview}
              isLoading={previewLoading}
              error={previewError}
            />
          )}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label htmlFor="bulk-approve-remark" className="text-sm">
                Remark <span className="text-destructive">*</span>
                <span className="ml-1 text-xs text-muted-foreground">(min {MIN_REMARK} chars)</span>
              </Label>
              <span
                className={`text-[11px] tabular-nums ${
                  remarkValid ? 'text-muted-foreground' : 'text-destructive'
                }`}
              >
                {trimmedLen} / {MAX_REMARK}
              </span>
            </div>
            <Textarea
              id="bulk-approve-remark"
              value={reason}
              onChange={(e) => setReason(e.target.value.slice(0, MAX_REMARK))}
              placeholder="e.g. Approved after Q-review meeting on 25 May 2026 — scores aligned with auditor."
              rows={3}
              disabled={isLoading}
              autoFocus
            />
            <p className="text-[11px] text-muted-foreground">
              This remark is recorded against every approved cell in the audit trail.
            </p>
          </div>

          <div className="space-y-1.5">
            <Label className="text-sm">
              Supporting evidence
              <span className="ml-1 text-xs text-muted-foreground">(optional, up to {MAX_FILES} files)</span>
            </Label>
            <MultiFileUpload
              userId={uploaderUserId}
              contextId={batchId}
              folder="bulk-approval"
              existingUrls={urls}
              onUploadComplete={setUrls}
              maxFiles={MAX_FILES}
              disabled={isLoading}
              label=""
            />
            {urls.length > 0 && (
              <p className="text-[11px] text-muted-foreground">
                {urls.length} file{urls.length === 1 ? '' : 's'} will be attached to all{' '}
                {cellCount} approved cell{cellCount === 1 ? '' : 's'}.
              </p>
            )}
          </div>

          {!remarkValid && trimmedLen > 0 && (
            <Alert variant="destructive" className="py-2">
              <AlertDescription className="text-xs">
                Please enter at least {MIN_REMARK} characters for the remark.
              </AlertDescription>
            </Alert>
          )}
        </div>

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={onCancel} disabled={isLoading}>
            Cancel
          </Button>
          <div className="flex flex-col items-end gap-1">
            <Button onClick={handleConfirm} disabled={!canSubmit}>
              {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              {isLoading
                ? `${verbing}…`
                : skippedCount > 0 && actionableCount > 0
                  ? `${verb} ${actionableCount} of ${cellCount}`
                  : `${verb} ${actionableCount} cell${actionableCount === 1 ? '' : 's'}`}
            </Button>
            {actionableCount === 0 && cellCount > 0 && (
              <p className="text-[11px] text-destructive">
                All cells lack prior scores and achievement values.
              </p>
            )}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}