// ADR-246 — thin CLI wrapper around the SSOT capture parser.
// Sources: CHANGELOG_2026.md, docs/adr/ADR-*.md, supabase/migrations/*.sql
// Floor: 2026-02-01. Idempotent: relies on uq_dev_report_entries_ingest_key.
// Parsing logic lives in src/lib/devReport/capture.ts — do NOT fork it here.
import { writeFileSync } from "node:fs";
import { collectDevReportRows } from "../plugins/devReportCapture";

const rows = collectDevReportRows(process.cwd());

const esc = (s: string) => s.replace(/'/g, "''");
const arr = (a: string[]) =>
  a.length ? `ARRAY[${a.map((x) => `'${esc(x)}'`).join(",")}]::text[]` : "ARRAY[]::text[]";
const lit = (v: string | null) => (v ? `'${esc(v)}'` : "NULL");

const lines = rows.map(
  (r) =>
    `(${[
      lit(r.entry_type),
      `'${r.entry_date}'::date`,
      lit(r.title),
      lit(r.description),
      lit(r.module_area),
      lit(r.status),
      lit(r.severity),
      lit(r.timeline_type),
      arr(r.adr_refs),
      lit(r.linked_commit),
      "NULL",
    ].join(",")})`,
);

const sql = `-- generated by scripts/devReportReseed.ts — DO NOT EDIT BY HAND
INSERT INTO public.dev_report_entries
  (entry_type, entry_date, title, description, module_area, status, severity, timeline_type, adr_refs, linked_commit, created_by)
VALUES
${lines.join(",\n")}
ON CONFLICT DO NOTHING;
`;
writeFileSync("/tmp/dev_report_reseed.sql", sql);

const byType: Record<string, number> = {};
const byMonth: Record<string, number> = {};
for (const r of rows) {
  byType[r.entry_type] = (byType[r.entry_type] ?? 0) + 1;
  byMonth[r.entry_date.slice(0, 7)] = (byMonth[r.entry_date.slice(0, 7)] ?? 0) + 1;
}
console.log(`Rows: ${rows.length}`);
console.log("By type:", byType);
console.log("By month:", byMonth);
console.log(`SQL bytes: ${sql.length}`);
