DROP POLICY IF EXISTS "Authenticated users can read non-sensitive settings" ON public.system_settings;

CREATE POLICY "Authenticated users can read allowlisted settings"
ON public.system_settings
FOR SELECT
TO authenticated
USING (
  setting_key = ANY (ARRAY[
    'auto_logout_minutes',
    'branding_company_name',
    'branding_loader_rocket_color',
    'branding_loader_show_logo',
    'branding_loader_tagline',
    'branding_max_size_mb',
    'compliance_exclude_bimonthly_not_due',
    'compliance_exclude_halfyearly_not_due',
    'compliance_exclude_org_kpi',
    'compliance_exclude_quarterly_not_due',
    'compliance_exclude_sent_back',
    'compliance_exclude_yearly_not_due',
    'compliance_penalty_auto_remark',
    'compliance_penalty_deadline_day',
    'compliance_penalty_enabled',
    'daily_aggregation_method',
    'dev_report_enabled',
    'dev_report.project_name',
    'dev_report.repository',
    'dev_report.tech_stack',
    'dev_report.workstreams',
    'employee_import_column_order',
    'employee_import_mandatory_fields',
    'employee_master_field_requirements',
    'enable_kpi_canonical_autolink',
    'evidence_allow_paste',
    'evidence_allowed_types',
    'evidence_max_files_per_kpi',
    'evidence_max_size_mb',
    'hub_enforcement_pilot_enabled',
    'hub_platform_settings_enabled',
    'image_compression_enabled',
    'image_compression_policy',
    'import_allowed_types',
    'import_background_threshold',
    'import_duplicate_handling',
    'import_max_rows',
    'import_max_size_mb',
    'kpi_import_column_order',
    'kpi_import_mandatory_fields',
    'kra_export_columns',
    'manager_penalty_auto_remark',
    'max_upload_size_mb',
    'menu_overrides_enabled',
    'pending_review_auto_remark',
    'pending_review_deadline_day',
    'pending_review_effective_from_month',
    'pms_pip_threshold',
    'report_overrides_enabled',
    'report_tile_overrides',
    'review_action_notes_visibility',
    'score_calculation_mode',
    'server_compression_enabled',
    'server_compression_pms_rewrite',
    'show_dummy_in_excel',
    'show_dummy_in_frontend'
  ]::text[])
);