DROP POLICY IF EXISTS "Admins and menu-override users can manage daily entries (delete" ON public.production_daily_entries;
CREATE POLICY "Admins and menu-override users can manage daily entries (delete" ON public.production_daily_entries FOR DELETE TO authenticated USING ((has_role(auth.uid(), 'admin'::app_role) OR has_menu_write_access(auth.uid(), 'incentive-config'::text, 'delete')));
DROP POLICY IF EXISTS "Admins and menu-override users can manage daily entries (insert" ON public.production_daily_entries;
CREATE POLICY "Admins and menu-override users can manage daily entries (insert" ON public.production_daily_entries FOR INSERT TO authenticated WITH CHECK ((has_role(auth.uid(), 'admin'::app_role) OR has_menu_write_access(auth.uid(), 'incentive-config'::text, 'add')));
DROP POLICY IF EXISTS "Admins and menu-override users can manage daily entries (update" ON public.production_daily_entries;
CREATE POLICY "Admins and menu-override users can manage daily entries (update" ON public.production_daily_entries FOR UPDATE TO authenticated USING ((has_role(auth.uid(), 'admin'::app_role) OR has_menu_write_access(auth.uid(), 'incentive-config'::text, 'update'))) WITH CHECK ((has_role(auth.uid(), 'admin'::app_role) OR has_menu_write_access(auth.uid(), 'incentive-config'::text, 'update')));
DROP POLICY IF EXISTS "Admins and menu-override users can manage production rates (del" ON public.incentive_production_rates;
CREATE POLICY "Admins and menu-override users can manage production rates (del" ON public.incentive_production_rates FOR DELETE TO authenticated USING ((has_role(auth.uid(), 'admin'::app_role) OR has_menu_write_access(auth.uid(), 'incentive-config'::text, 'delete')));
DROP POLICY IF EXISTS "Admins and menu-override users can manage production rates (ins" ON public.incentive_production_rates;
CREATE POLICY "Admins and menu-override users can manage production rates (ins" ON public.incentive_production_rates FOR INSERT TO authenticated WITH CHECK ((has_role(auth.uid(), 'admin'::app_role) OR has_menu_write_access(auth.uid(), 'incentive-config'::text, 'add')));
DROP POLICY IF EXISTS "Admins and menu-override users can manage production rates (upd" ON public.incentive_production_rates;
CREATE POLICY "Admins and menu-override users can manage production rates (upd" ON public.incentive_production_rates FOR UPDATE TO authenticated USING ((has_role(auth.uid(), 'admin'::app_role) OR has_menu_write_access(auth.uid(), 'incentive-config'::text, 'update'))) WITH CHECK ((has_role(auth.uid(), 'admin'::app_role) OR has_menu_write_access(auth.uid(), 'incentive-config'::text, 'update')));
DROP POLICY IF EXISTS "Incentive data entry users can manage daily entries (delete)" ON public.production_daily_entries;
CREATE POLICY "Incentive data entry users can manage daily entries (delete)" ON public.production_daily_entries FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'delete'));
DROP POLICY IF EXISTS "Incentive data entry users can manage daily entries (insert)" ON public.production_daily_entries;
CREATE POLICY "Incentive data entry users can manage daily entries (insert)" ON public.production_daily_entries FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'add'));
DROP POLICY IF EXISTS "Incentive data entry users can manage daily entries (update)" ON public.production_daily_entries;
CREATE POLICY "Incentive data entry users can manage daily entries (update)" ON public.production_daily_entries FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'update'));
DROP POLICY IF EXISTS "Incentive data users can delete production rates" ON public.incentive_production_rates;
CREATE POLICY "Incentive data users can delete production rates" ON public.incentive_production_rates FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'delete'));
DROP POLICY IF EXISTS "Incentive data users can delete vessel rates" ON public.incentive_vessel_rates;
CREATE POLICY "Incentive data users can delete vessel rates" ON public.incentive_vessel_rates FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'delete'));
DROP POLICY IF EXISTS "Incentive data users can insert eligibility" ON public.employee_incentive_eligibility;
CREATE POLICY "Incentive data users can insert eligibility" ON public.employee_incentive_eligibility FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'add'));
DROP POLICY IF EXISTS "Incentive data users can insert production rates" ON public.incentive_production_rates;
CREATE POLICY "Incentive data users can insert production rates" ON public.incentive_production_rates FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'add'));
DROP POLICY IF EXISTS "Incentive data users can insert vessel rates" ON public.incentive_vessel_rates;
CREATE POLICY "Incentive data users can insert vessel rates" ON public.incentive_vessel_rates FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'add'));
DROP POLICY IF EXISTS "Incentive data users can update eligibility" ON public.employee_incentive_eligibility;
CREATE POLICY "Incentive data users can update eligibility" ON public.employee_incentive_eligibility FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'update'));
DROP POLICY IF EXISTS "Incentive data users can update production rates" ON public.incentive_production_rates;
CREATE POLICY "Incentive data users can update production rates" ON public.incentive_production_rates FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'update'));
DROP POLICY IF EXISTS "Incentive data users can update vessel rates" ON public.incentive_vessel_rates;
CREATE POLICY "Incentive data users can update vessel rates" ON public.incentive_vessel_rates FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive-data'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can delete allocation rules" ON public.incentive_allocation_rules;
CREATE POLICY "Menu override users can delete allocation rules" ON public.incentive_allocation_rules FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete dq rules" ON public.incentive_disqualification_rules;
CREATE POLICY "Menu override users can delete dq rules" ON public.incentive_disqualification_rules FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete eligibility fields" ON public.incentive_eligibility_fields;
CREATE POLICY "Menu override users can delete eligibility fields" ON public.incentive_eligibility_fields FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete incentive mappings" ON public.incentive_program_mappings;
CREATE POLICY "Menu override users can delete incentive mappings" ON public.incentive_program_mappings FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete incentive programs" ON public.incentive_programs;
CREATE POLICY "Menu override users can delete incentive programs" ON public.incentive_programs FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete incentive slabs" ON public.incentive_slabs;
CREATE POLICY "Menu override users can delete incentive slabs" ON public.incentive_slabs FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete production targets" ON public.production_targets;
CREATE POLICY "Menu override users can delete production targets" ON public.production_targets FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete program types" ON public.incentive_program_types;
CREATE POLICY "Menu override users can delete program types" ON public.incentive_program_types FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete sub units" ON public.business_unit_sub_units;
CREATE POLICY "Menu override users can delete sub units" ON public.business_unit_sub_units FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete vessel entries" ON public.vessel_monthly_entries;
CREATE POLICY "Menu override users can delete vessel entries" ON public.vessel_monthly_entries FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can delete vessel rates" ON public.incentive_vessel_rates;
CREATE POLICY "Menu override users can delete vessel rates" ON public.incentive_vessel_rates FOR DELETE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'delete'));
DROP POLICY IF EXISTS "Menu override users can insert allocation rules" ON public.incentive_allocation_rules;
CREATE POLICY "Menu override users can insert allocation rules" ON public.incentive_allocation_rules FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert dq rules" ON public.incentive_disqualification_rules;
CREATE POLICY "Menu override users can insert dq rules" ON public.incentive_disqualification_rules FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert eligibility data" ON public.employee_incentive_eligibility;
CREATE POLICY "Menu override users can insert eligibility data" ON public.employee_incentive_eligibility FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert eligibility fields" ON public.incentive_eligibility_fields;
CREATE POLICY "Menu override users can insert eligibility fields" ON public.incentive_eligibility_fields FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert incentive mappings" ON public.incentive_program_mappings;
CREATE POLICY "Menu override users can insert incentive mappings" ON public.incentive_program_mappings FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert incentive programs" ON public.incentive_programs;
CREATE POLICY "Menu override users can insert incentive programs" ON public.incentive_programs FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert incentive records" ON public.employee_incentive_records;
CREATE POLICY "Menu override users can insert incentive records" ON public.employee_incentive_records FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert incentive slabs" ON public.incentive_slabs;
CREATE POLICY "Menu override users can insert incentive slabs" ON public.incentive_slabs FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert production targets" ON public.production_targets;
CREATE POLICY "Menu override users can insert production targets" ON public.production_targets FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert program types" ON public.incentive_program_types;
CREATE POLICY "Menu override users can insert program types" ON public.incentive_program_types FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert sub units" ON public.business_unit_sub_units;
CREATE POLICY "Menu override users can insert sub units" ON public.business_unit_sub_units FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert vessel entries" ON public.vessel_monthly_entries;
CREATE POLICY "Menu override users can insert vessel entries" ON public.vessel_monthly_entries FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can insert vessel rates" ON public.incentive_vessel_rates;
CREATE POLICY "Menu override users can insert vessel rates" ON public.incentive_vessel_rates FOR INSERT TO authenticated WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'add'));
DROP POLICY IF EXISTS "Menu override users can update allocation rules" ON public.incentive_allocation_rules;
CREATE POLICY "Menu override users can update allocation rules" ON public.incentive_allocation_rules FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update dq rules" ON public.incentive_disqualification_rules;
CREATE POLICY "Menu override users can update dq rules" ON public.incentive_disqualification_rules FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update eligibility data" ON public.employee_incentive_eligibility;
CREATE POLICY "Menu override users can update eligibility data" ON public.employee_incentive_eligibility FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update eligibility fields" ON public.incentive_eligibility_fields;
CREATE POLICY "Menu override users can update eligibility fields" ON public.incentive_eligibility_fields FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update incentive mappings" ON public.incentive_program_mappings;
CREATE POLICY "Menu override users can update incentive mappings" ON public.incentive_program_mappings FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update incentive programs" ON public.incentive_programs;
CREATE POLICY "Menu override users can update incentive programs" ON public.incentive_programs FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update incentive records" ON public.employee_incentive_records;
CREATE POLICY "Menu override users can update incentive records" ON public.employee_incentive_records FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update incentive slabs" ON public.incentive_slabs;
CREATE POLICY "Menu override users can update incentive slabs" ON public.incentive_slabs FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update production targets" ON public.production_targets;
CREATE POLICY "Menu override users can update production targets" ON public.production_targets FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update program types" ON public.incentive_program_types;
CREATE POLICY "Menu override users can update program types" ON public.incentive_program_types FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update score revisions" ON public.incentive_score_revisions;
CREATE POLICY "Menu override users can update score revisions" ON public.incentive_score_revisions FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update sub units" ON public.business_unit_sub_units;
CREATE POLICY "Menu override users can update sub units" ON public.business_unit_sub_units FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update vessel entries" ON public.vessel_monthly_entries;
CREATE POLICY "Menu override users can update vessel entries" ON public.vessel_monthly_entries FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));
DROP POLICY IF EXISTS "Menu override users can update vessel rates" ON public.incentive_vessel_rates;
CREATE POLICY "Menu override users can update vessel rates" ON public.incentive_vessel_rates FOR UPDATE TO authenticated USING (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update')) WITH CHECK (has_menu_write_access(auth.uid(), 'admin-incentive'::text, 'update'));